# Generated by Django 3.2 on 2021-04-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('SU', 'Supervisor'), ('CA', 'Caixa')], default='CA', max_length=2),
        ),
    ]
