# Generated by Django 3.2 on 2021-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('BE', 'Nível Supervisor'), ('BR', 'Nível Gerente')], default='BR', max_length=2),
        ),
    ]
