# Generated by Django 3.2 on 2021-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210427_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usuario_rede_social_facebook_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='usuario_rede_social_instagram_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='usuario_rede_social_twitter_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
