# Generated by Django 3.2 on 2021-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210427_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usuario_telefone_fixo',
            field=models.CharField(default='+55 000 11111111111', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='usuario_telefone_movel',
            field=models.CharField(default='+55 000 11111111111', max_length=200),
        ),
    ]
