# Generated by Django 3.2 on 2021-04-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('SU', 'Nível Supervisor'), ('CA', 'Nível Gerente')], default='CA', max_length=2),
        ),
    ]
