# Generated by Django 3.2 on 2021-04-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210427_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usuario_rede_social_facebook_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usuario_rede_social_instagram_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usuario_rede_social_twitter_link',
        ),
    ]
