# Generated by Django 3.2 on 2021-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(default='Fornecedor', max_length=200)),
                ('fornecedor_email', models.EmailField(blank=True, max_length=254)),
                ('fornecedor_endereco', models.CharField(default='Localization', max_length=200)),
                ('fornecedor_comentarios', models.TextField(blank=True)),
            ],
        ),
    ]
