# Generated by Django 3.2 on 2021-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='fornecedor_cidade',
            field=models.CharField(default='Localization', max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fornecedor_nome_empresa',
            field=models.CharField(default='Company', max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fornecedor_pais',
            field=models.CharField(default='Localization', max_length=200),
        ),
    ]
