# Generated by Django 3.2 on 2021-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_produto_venda_data_produto_produto_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_total_produtos', models.IntegerField(default=0)),
                ('estoque_total_ativo_produtos', models.IntegerField(default=0)),
                ('estoque_produtos_entrada', models.IntegerField(default=0)),
                ('estoque_produtos_saida', models.IntegerField(default=0)),
                ('produto_pk', models.ManyToManyField(to='products.Produto')),
            ],
        ),
    ]
