# Generated by Django 3.2 on 2021-04-17 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(default='Toninho', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(default='meu nome', max_length=200)),
                ('produto_quantidade', models.IntegerField(default=1)),
                ('produto_nome_vendedor', models.CharField(default='Juriscleyton', max_length=200)),
                ('produto_venda_data', models.DateField(default=datetime.date(2021, 4, 17))),
                ('fornecedor_pk', models.ManyToManyField(to='crud.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_produto_total', models.IntegerField(default=1)),
                ('estoque_entrada_produto', models.IntegerField(default=10)),
                ('estoque_saida_produto', models.IntegerField(default=10)),
                ('produto_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.produto')),
            ],
        ),
    ]
