# Generated by Django 3.2 on 2021-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('crud', '0003_auto_20210419_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor_pk',
            field=models.ManyToManyField(to='suppliers.Fornecedor'),
        ),
    ]
