# Generated by Django 3.2 on 2021-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_auto_20210420_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(default='Produto', max_length=200)),
                ('produto_tipo', models.CharField(choices=[('BE', 'coffee/tea, juice, soda'), ('BR', 'sandwich loaves, dinner rolls, tortillas, bagels'), ('CA', 'vegetables, spaghetti sauce, ketchup'), ('DA', 'cheeses, eggs, milk, yogurt, butter'), ('DR', 'cereals, flour, sugar, pasta, mixes'), ('FR', 'waffles, vegetables, individual meals, ice cream'), ('ME', 'lunch meat, poultry, beef, pork'), ('PR', 'fruits, vegetables'), ('CL', 'all - purpose, laundry detergent, dishwashing liquid/detergent'), ('PA', 'paper towels, toilet paper, aluminum foil, sandwich bags'), ('PE', 'shampoo, soap, hand soap, shaving cream'), ('OT', 'baby items, pet items, batteries, greeting cards')], default='OT', max_length=2)),
                ('produto_preco', models.FloatField(default=0.0)),
                ('produto_quantidade', models.IntegerField(default=1)),
                ('produto_nome_vendedor', models.CharField(default='Vendedor', max_length=200)),
                ('produto_venda_data', models.DateField(auto_now_add=True)),
                ('fornecedor_pk', models.ManyToManyField(to='suppliers.Fornecedor')),
            ],
        ),
    ]
