# Generated by Django 3.2 on 2021-04-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto_venda_data',
            new_name='produto_data_criacao',
        ),
    ]
